apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-jenkins
    labels:
        app: hello-jenkins
spec:
    replicas: 2
    selector:
        matchLabels:
            app: hello-jenkins
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: hello-jenkins
                tier: hello-jenkins
        spec:
            containers:
            - name: hello-jenkins
              image: udoyen/hello-jenkins
              imagePullPolicy: Always
              ports:
              - containerPort: 5000
                name: hello-jenkins

---
apiVersion: v1
kind: Service
metadata:
    name: hello-jenkins
    labels:
        app: hello-jenkins
spec:
    ports:
    - port: 5000
      targetPort: 5000
    selector:
        app: hello-jenkins
        tier: hello-jenkins
    type: LoadBalancer
